import { useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { api } from './api';

function useAuth() {
  const [state, setState] = useState({ loading: true, profile: null });

  const refreshAuth = () => {
    const token = localStorage.getItem('access_token');

    if (!token) {
      setState({ loading: false, profile: null });
      return;
    }

    setState(prev => ({ ...prev, loading: true }));

    api.me()
      .then(profile => setState({ loading: false, profile }))
      .catch(() => {
        localStorage.removeItem('access_token');
        setState({ loading: false, profile: null });
      });
  };

  useEffect(() => {
    refreshAuth();
  }, []);

  return { ...state, refreshAuth };
}

function App() {
  const auth = useAuth();
  const location = useLocation();
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }); }, [location.pathname]);
  const [toast, setToast] = useState(null);
  const notify = (message, kind = 'success') => { setToast({ message, kind }); window.setTimeout(() => setToast(null), 3200); };
  return <AuthContext.Provider value={auth}><ToastContext.Provider value={notify}><Layout /><div className="route-stage" key={location.pathname}><Routes>
    <Route path="/" element={<Landing />} /><Route path="/login" element={<Login />} />
    <Route path="/signup" element={<Signup />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password" element={<ResetPassword />} /><Route path="/events" element={<Events />} />
    <Route path="/events/:id" element={<EventDetails />} /><Route path="/403" element={<Forbidden />} />
    <Route path="/admin" element={<AdminEntry />} />
    <Route path="/my-registrations" element={<Guard><Registrations /></Guard>} />
    <Route path="/profile" element={<Guard><Profile /></Guard>} />
    <Route path="/admin/dashboard" element={<AdminGuard><Dashboard /></AdminGuard>} />
    <Route path="/admin/events" element={<AdminGuard><AdminEvents /></AdminGuard>} />
    <Route path="/admin/events/new" element={<AdminGuard><EventForm /></AdminGuard>} />
    <Route path="/admin/events/:id" element={<AdminGuard><AdminEventView /></AdminGuard>} />
    <Route path="/admin/events/:id/edit" element={<AdminGuard><EventForm /></AdminGuard>} />
    <Route path="/admin/events/:id/attendees" element={<AdminGuard><Attendees /></AdminGuard>} />
    <Route path="/admin/reports" element={<AdminGuard><Reports /></AdminGuard>} />
    <Route path="*" element={<NotFound />} />
  </Routes></div>{toast && <Toast {...toast} />}</ToastContext.Provider></AuthContext.Provider>;
}

import { createContext, useContext } from 'react';
const AuthContext = createContext({ loading: true, profile: null });
const ToastContext = createContext(() => {});
const useAuthState = () => useContext(AuthContext);
const useToast = () => useContext(ToastContext);

function Layout() {
  const { profile } = useAuthState(); const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const logout = () => { localStorage.removeItem('access_token'); navigate('/'); window.location.reload(); };
  const closeMenu = () => setMenuOpen(false);
  return <><header className={`topbar ${menuOpen ? 'menu-open' : ''}`}><Link to="/" className="brand" onClick={closeMenu}><span className="brand-mark">NE</span><span>Nowshera Events<span className="brand-dot">.</span></span></Link><button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button><nav className={menuOpen ? 'nav-open' : ''}>
    <Link to="/events" onClick={closeMenu}>Explore</Link>{profile?.role === 'admin' && <><Link to="/admin/dashboard" onClick={closeMenu}>Dashboard</Link><Link to="/admin/events" onClick={closeMenu}>Manage</Link><Link to="/admin/reports" onClick={closeMenu}>Reports</Link></>}
    {profile && profile.role !== 'admin' && <Link to="/my-registrations" onClick={closeMenu}>My registrations</Link>}
    {profile ? <><Link to="/profile" className="nav-profile" onClick={closeMenu}>{profile.full_name}</Link><button className="text-button" onClick={logout}>Log out</button></> : <><Link to="/login" onClick={closeMenu}>Log in</Link><Link to="/signup" className="nav-cta" onClick={closeMenu}>Create account</Link></>}
  </nav></header></>;
}

function Guard({ children }) { const { loading, profile } = useAuthState(); if (loading) return <Loading />; return profile ? children : <Navigate to="/login" replace />; }
function AdminGuard({ children }) { const { loading, profile } = useAuthState(); if (loading) return <Loading />; if (!profile) return <Navigate to="/login" replace />; return profile.role === 'admin' ? children : <Navigate to="/403" replace />; }
function AdminEntry() { const { loading, profile } = useAuthState(); if (loading) return <Loading />; if (!profile) return <Navigate to="/login" replace />; return profile.role === 'admin' ? <Navigate to="/admin/dashboard" replace /> : <Navigate to="/events" replace />; }
function Loading() { return <main className="page centered"><div className="spinner" /><p>Loading your workspace...</p></main>; }
function EventSkeleton() { return <div className="event-skeleton" aria-label="Loading event"><span /><span /><span /></div>; }
function Notice({ error, children }) { return <div className={error ? 'notice error' : 'notice'}>{children}</div>; }
function Toast({ message, kind }) { return <div className={`toast ${kind === 'error' ? 'toast-error' : ''}`} role="status"><span>{kind === 'error' ? '!' : '✓'}</span>{message}</div>; }
function ConfirmDialog({ title, description, confirmLabel, onConfirm, onCancel, busy }) { return <div className="modal-backdrop" role="presentation"><div className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><p className="eyebrow">Please confirm</p><h2 id="confirm-title">{title}</h2><p>{description}</p><div className="modal-actions"><button className="button ghost" onClick={onCancel} disabled={busy}>Cancel</button><button className="button primary" onClick={onConfirm} disabled={busy}>{busy ? 'Working...' : confirmLabel}</button></div></div></div>; }
function Page({ eyebrow, title, children, action }) { return <main className="page"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div>{children}</main>; }

function Landing() { return <main><section className="hero"><div className="hero-backdrop" /><div className="hero-copy"><p className="eyebrow">Nowshera Events Co. / 2026</p><h1>Make room for<br /><em>what matters.</em></h1><p className="hero-lede">A considered calendar of gatherings, ideas, and the people worth making time for.</p><div className="actions"><Link className="button primary magnetic" to="/events">Explore events <span>↗</span></Link><Link className="button ghost" to="/signup">Create an account</Link></div></div><div className="hero-art"><img src="/images/nowshera-night.jpg" alt="Nowshera city lights at night" /><div className="art-shade" /><div className="art-orbit" /><div className="art-label">NEXT UP <strong>01</strong></div><div className="art-date">15<br /><small>OCT</small></div><div className="art-caption">Nowshera<br /><strong>Tech Meetup</strong></div><span className="art-coordinate">34°00' N / 72°00' E</span></div></section><section className="intro-band"><span className="section-index">01 / THE CALENDAR</span><h2>For the curious,<br /><i>the connected,</i><br />the almost-there.</h2><p>Find the next room you want to be in. From sharp conversations to warm community tables, Nowshera Events keeps the good stuff close.</p><Link className="text-link" to="/events">View the calendar <span>↗</span></Link></section><section className="feature-strip"><div><span className="feature-no">01</span><h3>Find your people</h3><p>Browse experiences built around shared interests and local energy.</p></div><div><span className="feature-no">02</span><h3>Reserve with ease</h3><p>Simple registration with live availability and your plans in one place.</p></div><div><span className="feature-no">03</span><h3>Bring it together</h3><p>Admins get the tools to shape, publish, and understand every event.</p></div></section><footer className="footer"><Link className="brand" to="/"><span className="brand-mark">NE</span><span>Nowshera Events<span className="brand-dot">.</span></span></Link><span>Thoughtful events, close to home.</span><Link className="text-link" to="/events">Explore ↗</Link></footer></main>; }

function Events() { const [events, setEvents] = useState([]); const [status, setStatus] = useState('loading'); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [dateFilter, setDateFilter] = useState('all');
  useEffect(() => { api.events().then(data => { setEvents(data); setStatus('ready'); }).catch(() => setStatus('error')); }, []);
  const filtered = events.filter(e => { const matchesSearch = `${e.title} ${e.location}`.toLowerCase().includes(query.toLowerCase()); const matchesStatus = statusFilter === 'all' || e.status === statusFilter; const eventDate = new Date(`${e.event_date}T00:00`); const matchesDate = dateFilter === 'all' || (dateFilter === 'this-month' && eventDate.getMonth() === new Date().getMonth()) || (dateFilter === 'next-month' && eventDate.getMonth() === (new Date().getMonth() + 1) % 12); return matchesSearch && matchesStatus && matchesDate; });
  return <Page eyebrow="The calendar" title="Find your next thing." action={<div className="event-filters"><input className="search" placeholder="Search events" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Filter by status" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="published">Published</option><option value="completed">Completed</option></select><select aria-label="Filter by date" value={dateFilter} onChange={e => setDateFilter(e.target.value)}><option value="all">Any date</option><option value="this-month">This month</option><option value="next-month">Next month</option></select></div>}>
    {status === 'loading' && <div className="event-grid"><EventSkeleton /><EventSkeleton /></div>} {status === 'error' && <Notice error>Unable to load events. <button className="link-button" onClick={() => window.location.reload()}>Try again</button></Notice>}
    {status === 'ready' && !filtered.length && <Empty title="No upcoming events" text="Check back soon for something worth making time for." />}
    <div className="event-grid">{filtered.map(event => <EventCard key={event.id} event={event} />)}</div>
  </Page>;
}
function EventCard({ event }) { const image = event.title.toLowerCase().includes('tech') ? '/images/event-table.jpg' : '/images/event-gathering.jpg'; return <article className="event-card"><div className="card-visual"><img src={image} alt="" /><span className="card-date"><b>{new Date(`${event.event_date}T00:00`).toLocaleDateString('en', { day: '2-digit' })}</b><span>{new Date(`${event.event_date}T00:00`).toLocaleDateString('en', { month: 'short' })}</span></span></div><div className="card-body"><span className="tag">{event.status}</span><h2>{event.title}</h2><p>{event.description || 'An experience designed for curious people.'}</p><div className="meta"><span>◷ {event.event_time.slice(0, 5)}</span><span>⌖ {event.location}</span><span>{event.available_spots} spots left</span></div><Link className="card-link" to={`/events/${event.id}`}>View details <span>→</span></Link></div></article>; }

function EventDetails() { const { id } = useParams(); const { profile } = useAuthState(); const [event, setEvent] = useState(null); const [registrations, setRegistrations] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const notify = useToast();
  const load = () => { api.event(id).then(setEvent).catch(e => setError(e.message)); if (profile) api.registrations().then(setRegistrations).catch(() => {}); };
  useEffect(load, [id, profile]);
  if (error) return <Page eyebrow="Not found" title="This event moved on."><Notice error>{error}</Notice><Link className="button ghost" to="/events">Back to events</Link></Page>;
  if (!event) return <Loading />;
  const registration = registrations.find(r => r.event_id === event.id && r.status === 'active'); const closed = event.status !== 'published' || event.available_spots < 1;
  const register = async () => { setBusy(true); try { await api.register(id); load(); notify('Registration successful.'); } catch (e) { setError(e.message); notify(e.message, 'error'); } finally { setBusy(false); } };
  return <main className="page detail-page"><Link className="back" to="/events">← All events</Link><div className="detail-layout"><section><span className="tag">{event.status}</span><h1>{event.title}</h1><p className="detail-description">{event.description}</p><div className="detail-meta"><div><small>When</small><strong>{new Date(`${event.event_date}T00:00`).toLocaleDateString('en', { weekday: 'long', month: 'long', day: 'numeric' })}<br />{event.event_time.slice(0, 5)}</strong></div><div><small>Where</small><strong>{event.location}</strong></div><div><small>Availability</small><strong>{event.available_spots} of {event.capacity} spots</strong></div></div></section><aside className="action-panel"><p className="eyebrow">Save your seat</p>{!profile ? <><p>Join the room when it opens.</p><Link className="button primary full" to="/login">Log in to register</Link></> : registration ? <><p>You have a place at this event.</p><button className="button secondary full" disabled>Already registered</button></> : <><p>{closed ? (event.status === 'published' ? 'This event is full.' : 'Registration is closed.') : 'Ready when you are.'}</p><button className="button primary full" disabled={closed || busy} onClick={register}>{busy ? 'Reserving...' : closed ? 'Registration closed' : 'Register now'}</button></>}</aside></div></main>;
}

function AuthForm({ mode }) { const signup = mode === 'signup'; const [data, setData] = useState(signup ? { full_name: '', email: '', password: '' } : { email: '', password: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try { const result = signup ? await api.signup(data) : await api.login(data); if (result.session?.access_token) { localStorage.setItem('access_token', result.session.access_token); window.location.href = '/events'; } else { setMessage(result.message); } } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="auth-page"><div className="auth-panel"><p className="eyebrow">Nowshera Events Co.</p><h1>{signup ? 'Make yourself at home.' : 'Welcome back.'}</h1><p>{signup ? 'Create an account to keep your plans close.' : 'Pick up where you left off.'}</p>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<form onSubmit={submit}>{signup && <Field label="Full name" value={data.full_name} onChange={v => setData({ ...data, full_name: v })} />}<Field label="Email address" type="email" value={data.email} onChange={v => setData({ ...data, email: v })} /><Field label="Password" type="password" value={data.password} onChange={v => setData({ ...data, password: v })} />{!signup && <Link className="form-help" to="/forgot-password">Forgot your password?</Link>}<button className="button primary full" disabled={busy}>{busy ? 'Please wait...' : signup ? 'Create account' : 'Log in'}</button></form><p className="switch">{signup ? 'Already have an account?' : 'New here?'} <Link to={signup ? '/login' : '/signup'}>{signup ? 'Log in' : 'Create an account'}</Link></p></div></main>;
}
function Field({ label, type = 'text', value, onChange }) { return <label className="field"><span>{label}</span><input required type={type} value={value} onChange={e => onChange(e.target.value)} /></label>; }
const Login = () => <AuthForm mode="login" />; const Signup = () => <AuthForm mode="signup" />;
function ForgotPassword() { const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.forgotPassword({ email }); setMessage(result.message); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <main className="auth-page"><div className="auth-panel"><p className="eyebrow">Account recovery</p><h1>Find your way back.</h1><p>Enter your email and we will send a secure reset link if the account exists.</p>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<form onSubmit={submit}><Field label="Email address" type="email" value={email} onChange={setEmail} /><button className="button primary full" disabled={busy}>{busy ? 'Sending...' : 'Send reset link'}</button></form><p className="switch"><Link to="/login">← Back to login</Link></p></div></main>; }
function ResetPassword() { const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const token = new URLSearchParams(window.location.hash.replace(/^#/, '')).get('access_token'); const submit = async e => { e.preventDefault(); setError(''); if (!token) return setError('This reset link is missing or expired. Please request a new one.'); if (password !== confirm) return setError('Passwords do not match.'); setBusy(true); try { const result = await api.resetPassword({ password }, token); setMessage(result.message); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <main className="auth-page"><div className="auth-panel"><p className="eyebrow">Account recovery</p><h1>Choose a new password.</h1><p>Use at least eight characters, then return to login.</p>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<form onSubmit={submit}><Field label="New password" type="password" value={password} onChange={setPassword} /><Field label="Confirm password" type="password" value={confirm} onChange={setConfirm} /><button className="button primary full" disabled={busy || Boolean(message)}>{busy ? 'Updating...' : 'Update password'}</button></form><p className="switch"><Link to="/login">← Back to login</Link></p></div></main>; }

function Registrations() { const [items, setItems] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(null); const notify = useToast(); const load = () => {
  api.registrations()
    .then(setItems)
    .catch(e => setError(e.message));
};

useEffect(() => {
  load();
}, []); const cancel = async () => { setError(''); try { await api.cancelRegistration(pending); setPending(null); load(); notify('Registration cancelled.'); } catch (e) { setError(e.message); notify(e.message, 'error'); } }; return <Page eyebrow="Your plans" title="My registrations"><Notice error={error}>{error}</Notice>{items && !items.length && <Empty title="Nothing on the calendar yet" text="Your next good plan is a few clicks away." action={<Link className="button primary" to="/events">Browse events</Link>} />}{items && <div className="registration-list">{items.map(item => <div className="registration-row" key={item.id}><div><span className="tag">{item.status}</span><h2>{item.event.title}</h2><p>{item.event.event_date} · {item.event.location}</p></div><div className="row-actions"><Link className="button ghost" to={`/events/${item.event_id}`}>View event</Link>{item.status === 'active' && <button className="button danger" onClick={() => setPending(item.id)}>Cancel</button>}</div></div>)}</div>}{pending && <ConfirmDialog title="Cancel your registration?" description="Your seat will become available to someone else." confirmLabel="Cancel registration" onConfirm={cancel} onCancel={() => setPending(null)} />}</Page>; }
function Profile() { const { profile } = useAuthState(); const [name, setName] = useState(profile?.full_name || ''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const save = async e => { e.preventDefault(); try { await api.updateProfile({ full_name: name }); setMessage('Profile updated.'); } catch (err) { setError(err.message); } }; return <Page eyebrow="Account" title="Your profile"><div className="form-card"><Field label="Full name" value={name} onChange={setName} /><label className="field"><span>Email address</span><input value={profile?.email || ''} disabled /></label><label className="field"><span>Role</span><input value={profile?.role || ''} disabled /></label>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<button className="button primary" onClick={save}>Save profile</button></div></Page>; }

function AnimatedCounter({ value }) { const [display, setDisplay] = useState(0); useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return setDisplay(value); let current = 0; const step = Math.max(1, Math.ceil(value / 18)); const timer = window.setInterval(() => { current = Math.min(value, current + step); setDisplay(current); if (current === value) window.clearInterval(timer); }, 35); return () => window.clearInterval(timer); }, [value]); return <strong>{display}</strong>; }
function Dashboard() { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => api.summary().then(setData).catch(e => setError(e.message)), []); return <Page eyebrow="Admin workspace" title="Good morning, admin." action={<Link className="button primary" to="/admin/events/new">+ Create event</Link>}>{error && <Notice error>{error}</Notice>}{data && <div className="metrics">{[['Total events', data.total_events], ['Published', data.published_events], ['Upcoming', data.upcoming_events], ['Active registrations', data.active_registrations]].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><AnimatedCounter value={value} /></div>)}</div>}<div className="admin-links"><Link to="/admin/events"><span>01</span><strong>Manage events</strong><small>Create, edit and publish the calendar →</small></Link><Link to="/admin/reports"><span>02</span><strong>Reports</strong><small>Understand registrations and capacity →</small></Link></div></Page>; }
function AdminEvents() { const [events, setEvents] = useState([]); const [error, setError] = useState(''); const [pending, setPending] = useState(null); const notify = useToast(); const load = () => api.adminEvents().then(setEvents).catch(e => setError(e.message)); useEffect(load, []); const action = async (id, verb) => { try { await api.eventAction(id, verb); setPending(null); load(); notify(`Event ${verb === 'publish' ? 'published' : `${verb}d`}.`); } catch (e) { setError(e.message); notify(e.message, 'error'); } }; const requestAction = (id, verb) => verb === 'cancel' || verb === 'complete' ? setPending({ id, verb }) : action(id, verb); return <Page eyebrow="Admin workspace" title="Manage events" action={<Link className="button primary" to="/admin/events/new">+ Create event</Link>}>{error && <Notice error>{error}</Notice>}<div className="table-wrap"><table><thead><tr><th>Event</th><th>Date</th><th>Seats</th><th>Status</th><th /></tr></thead><tbody>{events.map(e => <tr key={e.id}><td><strong>{e.title}</strong><small>{e.location}</small></td><td>{e.event_date}</td><td>{e.active_registrations} / {e.capacity}</td><td><span className="tag">{e.status}</span></td><td className="table-actions"><Link to={`/admin/events/${e.id}/edit`}>Edit</Link><Link to={`/admin/events/${e.id}/attendees`}>Attendees</Link>{e.status === 'draft' && <button onClick={() => requestAction(e.id, 'publish')}>Publish</button>}{e.status === 'published' && <><button onClick={() => requestAction(e.id, 'complete')}>Complete</button><button onClick={() => requestAction(e.id, 'cancel')}>Cancel</button></>}</td></tr>)}</tbody></table></div>{pending && <ConfirmDialog title={`${pending.verb === 'cancel' ? 'Cancel' : 'Complete'} this event?`} description="This changes the event lifecycle and may close future attendee actions." confirmLabel={pending.verb} onConfirm={() => action(pending.id, pending.verb)} onCancel={() => setPending(null)} />}</Page>; }
function EventForm() { const { id } = useParams(); const edit = Boolean(id); const navigate = useNavigate(); const [form, setForm] = useState({ title: '', description: '', event_date: '', event_time: '', location: '', capacity: 50, status: 'draft' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { if (edit) api.adminEvent(id).then(e => setForm({ ...e, capacity: e.capacity, event_date: e.event_date, event_time: e.event_time.slice(0, 5) })).catch(e => setError(e.message)); }, [id]); const set = (key, value) => setForm({ ...form, [key]: value }); const submit = async e => { e.preventDefault(); setBusy(true); try { const data = { ...form, capacity: Number(form.capacity) }; if (edit) await api.updateEvent(id, data); else await api.createEvent(data); navigate('/admin/events'); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <Page eyebrow="Admin workspace" title={edit ? 'Edit event' : 'Create an event'}><div className="form-card wide">{error && <Notice error>{error}</Notice>}<form onSubmit={submit} className="event-form"><Field label="Title" value={form.title} onChange={v => set('title', v)} /><Field label="Location" value={form.location} onChange={v => set('location', v)} /><div className="form-row"><Field label="Date" type="date" value={form.event_date} onChange={v => set('event_date', v)} /><Field label="Time" type="time" value={form.event_time} onChange={v => set('event_time', v)} /><Field label="Capacity" type="number" value={form.capacity} onChange={v => set('capacity', v)} /></div><label className="field"><span>Description</span><textarea value={form.description || ''} onChange={e => set('description', e.target.value)} /></label><label className="field"><span>Status</span><select value={form.status} onChange={e => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><div className="actions"><Link className="button ghost" to="/admin/events">Cancel</Link><button className="button primary" disabled={busy}>{busy ? 'Saving...' : edit ? 'Update event' : 'Save event'}</button></div></form></div></Page>; }
function Attendees() { const { id } = useParams(); const [items, setItems] = useState(null); useEffect(() => api.attendees(id).then(setItems), [id]); return <Page eyebrow="Event details" title="Attendees"><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Registered</th></tr></thead><tbody>{items?.map(item => <tr key={`${item.id}-${item.registered_at}`}><td>{item.full_name}</td><td>{item.email}</td><td><span className="tag">{item.registration_status}</span></td><td>{new Date(item.registered_at).toLocaleDateString()}</td></tr>)}</tbody></table>{items?.length === 0 && <Empty title="No attendees yet" text="Registrations will appear here." />}</div></Page>; }
function AdminEventView() { const { id } = useParams(); const [event, setEvent] = useState(null); const [error, setError] = useState(''); useEffect(() => api.adminEvent(id).then(setEvent).catch(e => setError(e.message)), [id]); if (error) return <Page eyebrow="Admin workspace" title="Event unavailable"><Notice error>{error}</Notice><Link className="button ghost" to="/admin/events">Back to events</Link></Page>; if (!event) return <Loading />; return <Page eyebrow="Admin event view" title={event.title} action={<Link className="button primary" to={`/admin/events/${id}/edit`}>Edit event</Link>}><div className="detail-layout"><section><span className="tag">{event.status}</span><p className="detail-description">{event.description || 'No description provided.'}</p><div className="detail-meta"><div><small>Date</small><strong>{event.event_date}</strong></div><div><small>Location</small><strong>{event.location}</strong></div><div><small>Seats</small><strong>{event.active_registrations} / {event.capacity}</strong></div></div></section><aside className="action-panel"><p className="eyebrow">Attendee activity</p><p>Review the people registered for this event.</p><Link className="button primary full" to={`/admin/events/${id}/attendees`}>View attendees</Link></aside></div></Page>; }
function Reports() { const [data, setData] = useState(null); useEffect(() => api.summary().then(setData), []); return <Page eyebrow="Admin workspace" title="Reports & analytics"><div className="report-grid">{data && Object.entries({ 'Total events': data.total_events, 'Published events': data.published_events, 'All registrations': data.total_registrations, 'Active registrations': data.active_registrations, 'Completed events': data.completed_events, 'Cancelled events': data.cancelled_events }).map(([key, value]) => <div className="report-card" key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></Page>; }
function Empty({ title, text, action }) { return <div className="empty"><div className="empty-mark">○</div><h2>{title}</h2><p>{text}</p>{action}</div>; }
function Forbidden() { return <Page eyebrow="403" title="This room is for admins."><p>You do not have permission to view this page.</p><Link className="button primary" to="/events">Back to events</Link></Page>; }
function NotFound() { return <Page eyebrow="404" title="Page not found."><p>There is nothing here yet.</p><Link className="button primary" to="/">Return home</Link></Page>; }

export default App;
